version: '3.0'

services:
  grafana:
    container_name: 'sni-thruk-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.2.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/sni-thruk-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_USERS_DEFAULT_THEME=light
    depends_on:
      - buildwatch
  buildwatch:
    image: node:20
    command: bash -c "yarn install && yarn run dev"
    working_dir: /src
    volumes:
      - .:/src
